#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running Laravel Pint"
cmd="./vendor/bin/sail exec laravel.test ./vendor/bin/pint"
$cmd
status=$?
[ $status -eq 0 ] && echo "Pint scan done" || return
